//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclopesoft.Conceptual.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client : Person
    {
        public Client()
        {
            this.Product = new HashSet<Product>();
        }
    
        public string type { get; set; }
        public string Id_Fiscal { get; set; }
        public string RNC { get; set; }
        public string business_Name { get; set; }
        public string Directin { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
