//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclopesoft.Conceptual.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail : Invoice
    {
        public string Id_Product { get; set; }
        public string Amount { get; set; }
        public string Sale_Price { get; set; }
        public string Discout { get; set; }
    }
}
