//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclopesoft.Conceptual.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice : Client
    {
        public string Serie { get; set; }
        public string Payment_Type { get; set; }
        public string Client_Id { get; set; }
        public string User_Id { get; set; }
        public string Subtotal { get; set; }
        public string Taxes { get; set; }
        public string Total { get; set; }
        public string Status { get; set; }
    }
}
