//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclopesoft.Conceptual.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Bar_Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Distribution { get; set; }
        public string Image { get; set; }
        public string Cost_Price { get; set; }
        public string Gain { get; set; }
        public string Sale_Price { get; set; }
        public string Wholesale_Price { get; set; }
        public string Minimum { get; set; }
        public string Maximum { get; set; }
        public string Stock { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
